In [212]:
import cv2
import numpy as np

In [213]:
img = cv2.imread("images/joker.jpg", cv2.IMREAD_COLOR)

In [214]:
cv2.line(img, (10,10), (50, 50), (255,255,255), 5)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[ 93,  66,  29],
        [ 90,  63,  26],
        [ 86,  59,  22],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]],

       [[ 96,  67,  30],
        [ 95,  66,  29],
        [ 92,  63,  26],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]],

       [[105,  76,  39],
        [106,  77,  40],
        [105,  76,  39],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]]

In [215]:
cv2.line(img, (50,10), (10,50), (255,255,255), 5)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[ 93,  66,  29],
        [ 90,  63,  26],
        [ 86,  59,  22],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]],

       [[ 96,  67,  30],
        [ 95,  66,  29],
        [ 92,  63,  26],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]],

       [[105,  76,  39],
        [106,  77,  40],
        [105,  76,  39],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]]

In [216]:
cv2.rectangle(img, (10,10), (50,50), (0,255,255), 5)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[ 93,  66,  29],
        [ 90,  63,  26],
        [ 86,  59,  22],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]],

       [[ 96,  67,  30],
        [ 95,  66,  29],
        [ 92,  63,  26],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]],

       [[105,  76,  39],
        [106,  77,  40],
        [105,  76,  39],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]]

In [217]:
cv2.circle(img, (400,400), 100, (255,0,0), -1)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[ 93,  66,  29],
        [ 90,  63,  26],
        [ 86,  59,  22],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]],

       [[ 96,  67,  30],
        [ 95,  66,  29],
        [ 92,  63,  26],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]],

       [[105,  76,  39],
        [106,  77,  40],
        [105,  76,  39],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]]

In [218]:
addH = 100
addW = 100
pts = np.array([[10,400],[300,100],[400,50],[5,2]], np.int32)
pts[:,0] += addH
pts[:,1] += addW
pts = pts.reshape((-1,1,2))
cv2.polylines(img, [pts], True, (0,255,255), 3)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[ 93,  66,  29],
        [ 90,  63,  26],
        [ 86,  59,  22],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]],

       [[ 96,  67,  30],
        [ 95,  66,  29],
        [ 92,  63,  26],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]],

       [[105,  76,  39],
        [106,  77,  40],
        [105,  76,  39],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]]

In [219]:
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(img, "Here text", (100, 800), font, 10, (100,255,255), 20, cv2.LINE_AA)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[ 93,  66,  29],
        [ 90,  63,  26],
        [ 86,  59,  22],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]],

       [[ 96,  67,  30],
        [ 95,  66,  29],
        [ 92,  63,  26],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]],

       [[105,  76,  39],
        [106,  77,  40],
        [105,  76,  39],
        ...,
        [  5,   1,   0],
        [  5,   1,   0],
        [  5,   1,   0]]

In [220]:
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()